### ISSUE TITLE
Stop download once first frame is received?

### ISSUE THREAD

**Issue by jmcbee** [adamfur/GifJam#7]
Is it possible?

**Comment by adamfur** [comment]
Does it even matter? Gifs are generally only a few kilobytes small.

**Comment by fbm-static** [comment]
If you're on a metered bandwidth, it does. There's no need to be rude, it was just an inquiry.

**Comment by adamfur** [comment]
Was honestly curious if you had a use case, where your browser is chugging down huge gifs.
In theory you can drop the connection after you have received just the first frame, as all the metadata is isolated in the beginning of the file. If you can accomplish that with the chrome plugin api, I doubt you can, but don't know for sure.
